Fix the handling of the "no files to check" case
Currently, it causes Checkton to fail with

    ❌ Found ShellCheck warnings! /o\
    Error: EOF while parsing a value at line 1 column 0

(Note that Checkton also erroneously thinks there are some ShellCheck
warnings.)

Signed-off-by: Adam Cmiel <acmiel@redhat.com>